### ISSUE TITLE
DQ: CCDA data for Other Counts

### ISSUE THREAD

**Issue by chrisroederucdenver** [cladteam/CCDA_OMOP_by_Python#134]
This is a ticket for the backend work for the seccond batch of metrics, here on the CCDA side.

- [x]  data of diagnoses per person
  - [x] include support for the count of 0%  
- [x] data of measurements per person
- [x] data of observation per person
If the widget doesn't automatically create buckets, do something reasonable and compare it to what was done in the N3C dashboards.

**Comment by AdamLeeIT** [comment]
The datasets for `ccda_counts_by_measurement`, `ccda_counts_by_observation`, and `ccda_counts_by_condition` are available in Slate. The JHU crosswalk tables are now being used. 

For ccda_counts_by_condition
_comment the section_code = '1145-4'. In fact, it should be != 10157-6 the one for family history. The idea is that if there is a section we overlooked, it will show up. This will work if exclude family history rather than restricting to problem list._
This may result in some additional counts that skew the numbers, depending on 'what' we intend in our counts. For example if we want to count total instances of 'code="64109004" displayName="Costal Chondritis"' for a patient, then 3 would be the answer for CCDA 170.314b2_AmbulatoryToC.xml. However, if we want the number of conditions for Costal Chondritis on the patient, then 1 would be the answer. It appears 1 time in the Problem Section, 1 time as a reason for Plan of Care section, and 1 time as a reason in the Encounter Section. Total instances is what is currently being counted.

Code was corrected comment out value_type not in ('CD','CE') for observation and measurement (shouldn't have been on observation) The intent was to remove rows like Diagnosis status [concept_id 3030068 LOINC ] that is used in an element called entryRelationship that declares the status of the test result, like as in final or cancelled. It is in a `code` element and picked up. It is likely better to include these codes as 'noise' rather than remove them at this point (thus the commented out SQL) having only 1 example isn't evidence enough to eliminate all CD/CE values for measurement. 

`<entryRelationship typeCode="REFR" inversionInd="false">
<observation classCode="OBS" moodCode="EVN">
<templateId root="2.16.840.1.113883.10.20.1.57"></templateId>
<code code="33999-4" displayName="Status" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LN"></code>
<text></text>
<statusCode code="completed"></statusCode>
<value xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" code="final" codeSystem="2.16.840.1.113883.5.14" codeSystemName="ActStatus" displayName="final" xsi:type="CE">
<originalText>final</originalText>
</value>
</observation>
</entryRelationship>`

I no longer see double 'Age at onset of clinical finding' rows so that should be resolved

**Comment by chrisroederucdenver** [comment]
@Adam if you comment code here you should include what file and repo you're discussing. Preferably, many of these comments belong in the code where they will be immediately useful to readers. There are no links in the code to this repo, or this ticket.

I see the CD, CE thing in ccda_counts_by_measurement. As commented out code, the complexity above is less important. The line of code should be fully removed. It's noise, as is the older code block commented out at the bottom.

After looking at each of the other files I see the code that excludes family history, in the ccda_counts_by_condition.sql file, and the comment that describes why. This is as it should be. 
There are some dead column names and a commented out "ON TRUE" in there that can be cleaned up.
Realize that when I worked on this code, I was treading lightly, respecting it as yours. It was also wasn't meant as my final commit.

**Comment by chrisroederucdenver** [comment]
Good after review.
